# 1.首先，在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作。
# 工作流名称
name: Sync-Images-to-AliDocker
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to AliDocker.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job 并指定使用的操作系统环境。
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    # 在job中添加步骤来执行同步操作。在上述job中，添加步骤来执行skopeo命令，从registry.k8s.io仓库拉取镜像，并将其推送到docker.io仓库。
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    # 设置项目Secrets以提供Docker Hub登录所需的用户名和密码。
    - name: Login to alidocker
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_LOGIN_URL }}
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}
        logout: false
    # - name: 登录dockerhub
    #   run: docker login --username=yshyq --password=7648@qq.com hub.docker.com

    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: 同步镜像
      run: |
        #!/usr/bin/env bash
        #skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-apiserver:v1.27.4
        #skopeo copy --all docker://node:18-alpine3.20 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/node:18-alpine3.20
        #skopeo copy --all docker://gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nfs-subdir-external-provisioner:v4.0.2
        # skopeo copy --all docker://minio/minio:RELEASE.2023-10-16 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-10-16
        # skopeo copy --all docker://docker.io/anjia0532/google-containers.ingress-nginx.kube-webhook-certgen:v1.1.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/google-containers.ingress-nginx.kube-webhook-certgen:v1.1.1
        # skopeo copy --all docker://docker.io/grafana/promtail:2.8.3 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-promtail:2.8.3

        # skopeo copy --all docker://grafana/grafana:9.3.16 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana:9.3.16
        # # skopeo copy --all docker://docker.io/grafana/promtail:2.8.3 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-promtail:2.8.3
        # skopeo copy --all docker://grafana/loki:2.6.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-loki:2.6.1


        # skopeo copy --all docker://docker.io/flannel/flannel:v0.25.5 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel:v0.25.5
        # skopeo copy --all docker://docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1
        # docker pull docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1
        # docker tag  docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1


        # skopeo copy --all docker://mysql:5.7 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7

        # docker pull mysql:5.7
        # docker tag  mysql:5.7 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7


        docker pull easzlab/kubeasz-k8s-bin:v1.25.9
        docker tag easzlab/kubeasz-k8s-bin:v1.25.9 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-k8s-bin:v1.25.9
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-k8s-bin:v1.25.9
        
        docker pull easzlab/kubeasz-ext-bin:1.7.1
        docker tag easzlab/kubeasz-ext-bin:1.7.1 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-ext-bin:1.7.1
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-ext-bin:1.7.1
        
        docker pull easzlab/kubeasz-sys-pkg:0.5.2
        docker tag easzlab/kubeasz-sys-pkg:0.5.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-sys-pkg:0.5.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-sys-pkg:0.5.2
        
        docker pull easzlab/harbor-offline:v2.6.3
        docker tag easzlab/harbor-offline:v2.6.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/harbor-offline:v2.6.3
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/harbor-offline:v2.6.3
        
        docker pull calico/cni:v3.24.5
        docker tag calico/cni:v3.24.5 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-cni:v3.24.5
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-cni:v3.24.5
        
        docker pull calico/kube-controllers:v3.24.5
        docker tag calico/kube-controllers:v3.24.5 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-kube-controllers:v3.24.5
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-kube-controllers:v3.24.5
        
        docker pull calico/node:v3.24.5
        docker tag calico/node:v3.24.5 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-node:v3.24.5
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/calico-node:v3.24.5
        
        docker pull coredns/coredns:1.9.3
        docker tag coredns/coredns:1.9.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/coredns:1.9.3
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/coredns:1.9.3
        
        
        docker pull easzlab/k8s-dns-node-cache:1.22.13
        docker tag easzlab/k8s-dns-node-cache:1.22.13 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/k8s-dns-node-cache:1.22.13
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/k8s-dns-node-cache:1.22.13
        
        docker pull kubernetesui/dashboard:v2.7.0
        docker tag kubernetesui/dashboard:v2.7.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubernetesui-dashboard:v2.7.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubernetesui-dashboard:v2.7.0
        
        docker pull kubernetesui/metrics-scraper:v1.0.8
        docker tag kubernetesui/metrics-scraper:v1.0.8 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubernetesui-metrics-scraper:v1.0.8
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubernetesui-metrics-scraper:v1.0.8
        
        docker pull easzlab/metrics-server:v0.5.2
        docker tag easzlab/metrics-server:v0.5.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/metrics-server:v0.5.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/metrics-server:v0.5.2




        docker pull easzlab/kubeasz:3.4.6
        docker tag easzlab/kubeasz:3.4.6 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz:3.4.6
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz:3.4.6
        
        docker pull rancher/mirrored-flannelcni-flannel:v0.19.2
        docker tag rancher/mirrored-flannelcni-flannel:v0.19.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mirrored-flannelcni-flannel:v0.19.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mirrored-flannelcni-flannel:v0.19.2

        docker pull rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0 
        docker tag rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0  registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mirrored-flannelcni-flannel-cni-plugin:v1.1.0 
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mirrored-flannelcni-flannel-cni-plugin:v1.1.0 

        docker pull easzlab/nfs-subdir-external-provisioner:v4.0.2
        docker tag easzlab/nfs-subdir-external-provisioner:v4.0.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nfs-subdir-external-provisioner:v4.0.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nfs-subdir-external-provisioner:v4.0.2

   

        docker pull cilium/operator-generic:1.12.4
        docker tag cilium/operator-generic:1.12.4 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-operator-generic:1.12.4
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-operator-generic:1.12.4

        docker pull cilium/hubble-relay:1.12.4
        docker tag cilium/hubble-relay:1.12.4 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-relay:1.12.4
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-relay:1.12.4

        docker pull cilium/hubble-ui-backend:v0.9.2 
        docker tag cilium/hubble-ui-backend:v0.9.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-ui-backend:v0.9.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-ui-backend:v0.9.2

        docker pull cilium/hubble-ui:v0.9.2 
        docker tag cilium/hubble-ui:v0.9.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-ui:v0.9.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/cilium-hubble-ui:v0.9.2

        docker pull easzlab/json-mock:v1.3.0
        docker tag easzlab/json-mock:v1.3.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/json-mock:v1.3.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/json-mock:v1.3.0

        docker pull easzlab/alpine-curl:v7.85.0
        docker tag easzlab/alpine-curl:v7.85.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/alpine-curl:v7.85.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/alpine-curl:v7.85.0

        docker pull easzlab/kube-state-metrics:v2.5.0
        docker tag easzlab/kube-state-metrics:v2.5.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123kube-state-metrics:v2.5.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-state-metrics:v2.5.0

        docker pull easzlab/kube-webhook-certgen:v1.2.0 
        docker tag easzlab/kube-webhook-certgen:v1.2.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-webhook-certgen:v1.2.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-webhook-certgen:v1.2.0

        docker pull grafana/grafana:9.0.5
        docker tag grafana/grafana:9.0.5 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana:9.0.5
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana:9.0.5

        docker pull quay.io/kiwigrid/k8s-sidecar:1.19.2
        docker tag quay.io/kiwigrid/k8s-sidecar:1.19.2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/k8s-sidecar:1.19.2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/k8s-sidecar:1.19.2

        docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.58.0 
        docker tag quay.io/prometheus-operator/prometheus-config-reloader:v0.58.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus-config-reloader:v0.58.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus-config-reloader:v0.58.0

        docker pull quay.io/prometheus-operator/prometheus-operator:v0.58.0 
        docker tag quay.io/prometheus-operator/prometheus-operator:v0.58.0  registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus-operator:v0.58.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus-operator:v0.58.0

        docker pull quay.io/prometheus/alertmanager:v0.24.0 
        docker tag  quay.io/prometheus/alertmanager:v0.24.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/alertmanager:v0.24.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/alertmanager:v0.24.0

        docker pull quay.io/prometheus/node-exporter:v1.3.1 
        docker tag quay.io/prometheus/node-exporter:v1.3.1  registry.cn-hangzhou.aliyuncs.com/mytest_docker123/node-exporter:v1.3.1
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/node-exporter:v1.3.1

        docker pull quay.io/prometheus/prometheus:v2.37.0 
        docker tag quay.io/prometheus/prometheus:v2.37.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus:v2.37.0
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/prometheus:v2.37.0

        docker pull registry:2
        docker tag registry:2 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/registry:2
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/registry:2




        # docker pull  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231226-1a7112e06@sha256:25d6a5f11211cc5c3f9f2bf552b585374af287b4debf693cacbe2da47daa5084
        # docker tag  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231226-1a7112e06@sha256:25d6a5f11211cc5c3f9f2bf552b585374af287b4debf693cacbe2da47daa5084 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-webhook-certgen:v2023122
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-webhook-certgen:v2023122
    


        
        # skopeo copy --all docker://chen:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/chen:v4.1.0-ce

        # skopeo copy --all docker://core:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/core:v4.1.0-ce

        # skopeo copy --all docker://koko:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/koko:v4.1.0-ce

        # skopeo copy --all docker://lion:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/lion:v4.1.0-ce

        # skopeo copy --all docker://postgres:16.3-bullseye docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/postgres:16.3-bullseye

