# 1.首先，在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作。
# 工作流名称
name: Sync-Images-to-AliDocker
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to AliDocker.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job 并指定使用的操作系统环境。
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    # 在job中添加步骤来执行同步操作。在上述job中，添加步骤来执行skopeo命令，从registry.k8s.io仓库拉取镜像，并将其推送到docker.io仓库。
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    # 设置项目Secrets以提供Docker Hub登录所需的用户名和密码。
    - name: Login to alidocker
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_LOGIN_URL }}
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}
        logout: false
    # - name: 登录dockerhub
    #   run: docker login --username=yshyq --password=7648@qq.com hub.docker.com

    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: 同步镜像
      run: |
        #!/usr/bin/env bash
        #skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kube-apiserver:v1.27.4
        #skopeo copy --all docker://node:18-alpine3.20 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/node:18-alpine3.20
        #skopeo copy --all docker://gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nfs-subdir-external-provisioner:v4.0.2
        # skopeo copy --all docker://minio/minio:RELEASE.2023-10-16 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-10-16
        # skopeo copy --all docker://docker.io/anjia0532/google-containers.ingress-nginx.kube-webhook-certgen:v1.1.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/google-containers.ingress-nginx.kube-webhook-certgen:v1.1.1
        # skopeo copy --all docker://docker.io/grafana/promtail:2.8.3 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-promtail:2.8.3

        # skopeo copy --all docker://grafana/grafana:9.3.16 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana:9.3.16
        # # skopeo copy --all docker://docker.io/grafana/promtail:2.8.3 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-promtail:2.8.3
        # skopeo copy --all docker://grafana/loki:2.6.1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/grafana-loki:2.6.1


        # skopeo copy --all docker://docker.io/flannel/flannel:v0.25.5 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel:v0.25.5
        # skopeo copy --all docker://docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1
        # docker pull docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1
        # docker tag  docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/flannel-cni-plugin:v1.5.1-flannel1


        # skopeo copy --all docker://mysql:5.7 docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7

        # docker pull mysql:5.7
        # docker tag  mysql:5.7 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:5.7


        # docker pull easzlab/kubeasz-k8s-bin:v1.25.9
        # docker tag easzlab/kubeasz-k8s-bin:v1.25.9 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-k8s-bin:v1.25.9
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kubeasz-k8s-bin:v1.25.9
        
      
   
   

       


        # docker pull langgenius/dify-api:0.15.3
        # docker tag langgenius/dify-api:0.15.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-api:0.15.3
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-api:0.15.3
        
        # docker pull langgenius/dify-web:0.15.3
        # docker tag langgenius/dify-web:0.15.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-web:0.15.3
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-web:0.15.3
 
        # docker pull postgres:15-alpine
        # docker tag postgres:15-alpine registry.cn-hangzhou.aliyuncs.com/mytest_docker123/postgres:15-alpine
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/postgres:15-alpine
        
        # docker pull redis:6-alpine
        # docker tag redis:6-alpine registry.cn-hangzhou.aliyuncs.com/mytest_docker123/redis:6-alpine
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/redis:6-alpine

        # docker pull langgenius/dify-sandbox:0.2.10
        # docker tag langgenius/dify-sandbox:0.2.10 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-sandbox:0.2.10
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-sandbox:0.2.10

        # docker pull langgenius/dify-plugin-daemon:0.0.2-local
        # docker tag langgenius/dify-plugin-daemon:0.0.2-local registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-plugin-daemon:0.0.2-local
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-dify-plugin-daemon:0.0.2-local

        # docker pull ubuntu/squid:latest
        # docker tag ubuntu/squid:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/ubuntu-squid:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/ubuntu-squid:latest

        # docker pull certbot/certbot
        # docker tag certbot/certbot registry.cn-hangzhou.aliyuncs.com/mytest_docker123/certbot
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/certbot

        # docker pull nginx:latest
        # docker tag nginx:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nginx:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/nginx:latest

        # docker pull semitechnologies/weaviate:1.19.0
        # docker tag semitechnologies/weaviate:1.19.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/semitechnologies-weaviate:1.19.0
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/semitechnologies-weaviate:1.19.0

        # docker pull langgenius/qdrant:v1.7.3
        # docker tag langgenius/qdrant:v1.7.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-qdrant:v1.7.3
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/langgenius-qdrant:v1.7.3

        # docker pull pgvector/pgvector:pg16
        # docker tag pgvector/pgvector:pg16 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/pgvector-pgvector:pg16
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/pgvector-pgvector:pg16

        # docker pull tensorchord/pgvecto-rs:pg16-v0.3.0
        # docker tag tensorchord/pgvecto-rs:pg16-v0.3.0 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/tensorchord-pgvecto-rs:pg16-v0.3.0
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/tensorchord-pgvecto-rs:pg16-v0.3.0
  
        # docker pull ghcr.io/chroma-core/chroma:0.5.20
        # docker tag ghcr.io/chroma-core/chroma:0.5.20 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/chroma:0.5.20
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/chroma:0.5.20
  
        # docker pull quay.io/oceanbase/oceanbase-ce:4.3.3.0-100000142024101215
        # docker tag quay.io/oceanbase/oceanbase-ce:4.3.3.0-100000142024101215 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/oceanbase-ce:4.3.3.0-100000142024101215
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/oceanbase-ce:4.3.3.0-100000142024101215
  
        # docker pull container-registry.oracle.com/database/free:latest
        # docker tag container-registry.oracle.com/database/free:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/database-free:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/database-free:latest
  
        # docker pull quay.io/coreos/etcd:v3.5.5
        # docker tag quay.io/coreos/etcd:v3.5.5 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/etcd:v3.5.5
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/etcd:v3.5.5
  
        # docker pull minio/minio:RELEASE.2023-03-20T20-16-18Z
        # docker tag minio/minio:RELEASE.2023-03-20T20-16-18Z registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-03-20T20-16-18Z
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-03-20T20-16-18Z
  
        # docker pull milvusdb/milvus:v2.5.0-beta
        # docker tag milvusdb/milvus:v2.5.0-beta registry.cn-hangzhou.aliyuncs.com/mytest_docker123/milvus:v2.5.0-beta
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/milvus:v2.5.0-beta
  
        # docker pull opensearchproject/opensearch:latest
        # docker tag opensearchproject/opensearch:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/opensearch:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/opensearch:latest
  
        # docker pull opensearchproject/opensearch-dashboards:latest
        # docker tag opensearchproject/opensearch-dashboards:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/opensearch-dashboards:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/opensearch-dashboards:latest
  
        # docker pull myscale/myscaledb:1.6.4
        # docker tag myscale/myscaledb:1.6.4 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/myscaledb:1.6.4
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/myscaledb:1.6.4
  
        # docker pull docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        # docker tag docker.elastic.co/elasticsearch/elasticsearch:8.14.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/elasticsearch:8.14.3
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/elasticsearch:8.14.3
  
        # docker pull docker.elastic.co/kibana/kibana:8.14.3
        # docker tag docker.elastic.co/kibana/kibana:8.14.3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kibana:8.14.3
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/kibana:8.14.3
  
        # docker pull downloads.unstructured.io/unstructured-io/unstructured-api:latest
        # docker tag downloads.unstructured.io/unstructured-io/unstructured-api:latest registry.cn-hangzhou.aliyuncs.com/mytest_docker123/unstructured-api:latest
        # docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/unstructured-api:latest




        docker pull infiniflow/ragflow:v0.16.0-slim
        docker tag infiniflow/ragflow:v0.16.0-slim registry.cn-hangzhou.aliyuncs.com/mytest_docker123/infiniflow-ragflow:v0.16.0-slim
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/infiniflow-ragflow:v0.16.0-slim
        
        docker pull edwardelric233/ragflow:oc9
        docker tag edwardelric233/ragflow:oc9 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/edwardelric233-ragflow:oc9
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/edwardelric233-ragflow:oc9

        docker pull infiniflow/infinity:v0.6.0-dev3
        docker tag infiniflow/infinity:v0.6.0-dev3 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/infiniflow-infinity:v0.6.0-dev3
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/infiniflow-infinity:v0.6.0-dev3
        
        docker pull mysql:8.0.39
        docker tag mysql:8.0.39 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:8.0.39
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/mysql:8.0.39

        docker pull quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
        docker tag quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-12-20T01-00-02Z
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/minio:RELEASE.2023-12-20T01-00-02Z
        
        docker pull valkey/valkey:8
        docker tag valkey/valkey:8 registry.cn-hangzhou.aliyuncs.com/mytest_docker123/valkey/valkey:8
        docker push registry.cn-hangzhou.aliyuncs.com/mytest_docker123/valkey/valkey:8

        # skopeo copy --all docker://chen:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/chen:v4.1.0-ce

        # skopeo copy --all docker://core:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/core:v4.1.0-ce

        # skopeo copy --all docker://koko:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/koko:v4.1.0-ce

        # skopeo copy --all docker://lion:v4.1.0-ce docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/lion:v4.1.0-ce

        # skopeo copy --all docker://postgres:16.3-bullseye docker://registry.cn-hangzhou.aliyuncs.com/mytest_docker123/postgres:16.3-bullseye

